# -*- coding: utf-8 -*-
"""Classes&Objects.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AZeZRciDVo-5adrTU0lwzjWZJOdjFqBv
"""

class Student:
  name = "Sana"
  fav_sub = "Maths"
  def info(self):
    print(f"{self.name} loves {self.fav_sub}.")
a=Student()
a.info()
b =Student()
b.name="Zain"
b.fav_sub="English"
b.info()
c = Student()
c.name="Hana"
c.fav_sub="SST"
c.info()

#Using Constructor:
class Student:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def info(self):
    print(f"{self.name} is {self.age}.")

a = Student("Sara",18)
b = Student("Zain",16)
c = Student("John",19)
a.info()
b.info()
c.info()

