# -*- coding: utf-8 -*-
"""Custom_errors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vk4XW1RH3HF7ZCxEfmiryRxePDfeT0Te
"""

a = input("Enter the string: ")
if a=='quit':
  print(5*2)
else:
    raise ValueError("Value entered is wrong")

a = int(input("Enter the value between 2 and 8: "))
if a<2 or a>8:
  raise ValueError("Value entered is not right")

