# -*- coding: utf-8 -*-
"""DataTypesproblemset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uFTTVlaudUA8dYQzEg6xZBp2RKcE0y98
"""

#Printing sum of two numbers:
x = int(input("Enter the value of x: "))
y = int(input("Enter the value of y: "))
sum = x+y
print(f"The sum of {x} and {y} is:{sum} ")

#Printing area of square:
l = float(input("Enter the value of side: "))
sq = l*l
print(f"The area of square with side {l} is:{sq} ")

#Printing area of rectangle:
l =float(input("l: "))
b =float(input("b: "))
area = l*b
print("The area of rectangle is :",area)

