# -*- coding: utf-8 -*-
"""Dictionary_mod2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13p6ymnbLWkFmdUKqHUf8LUckHCaGbbPr
"""

dic = {1:'Day','Month':'March'}
print(dic)

dic = {'Monday':'Day','Month':['March',19]}
print(dic)

dic = dict([(1,'Monday'),(2,'Tuesday')])
print(dic)

dic = dict([(1,'Monday'),(2,'Tuesday')])
print(dic[1])

dic = dict([(1,'Monday'),(2,'Tuesday')])
print(dic[3])

dic = dict([(1,'Monday'),(2,'Tuesday')])
print(dic.get(1))

dic = dict([(1,'Monday'),(2,'Tuesday')])
dic[1]='Sunday'
print(dic)

dic = dict([(1,'Monday'),(2,'Tuesday')])
dic['Month'] = 'March'
print(dic)

dic = dict([(1,'Monday'),(2,'Tuesday')])
dic.pop(2)
print(dic)

squares = {2:4,3:9,4:16}
del squares[2]
print(squares)

squares = {2:4,3:9,4:16}
dic = squares.copy()
print(dic)

subjects = {}.fromkeys(['Math','English','Science'],10)
print(subjects)

squares = {2:4,3:9,4:16}
print(squares.items())

squares = {2:4,3:9,4:16}
print(squares.keys())

squares = {2:4,3:9,4:16}
print(squares.values())

d = {}
print(dir(d))

d = {'a':1,'b':2,'c':3,'d':4}
new_d= {k:v for k,v in d.items() if v>2}
print(new_d)

