# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yksZdDdOOCBQU2ljTFBj7xBwxQN95sHZ
"""

info ={"name":"Zakir", "age": 17, "residence":"Noida"}
print(info)

print(info['name'])

print(info.keys())
print(info.values())

for key in info.keys():
  print(info[key])

print(info.items())

for key,value in info.items():
  print(key,value)

ep1 = {122:45,126:89,567:69,670:69}
ep2 = {222:67,566:90}
ep1.update(ep2)

print(ep1)

ep1.pop(122)

print(ep1)

ep1.popitem()

print(ep1)

del ep1[126]

print(ep1)

ep2.clear()

print(ep2)

