# -*- coding: utf-8 -*-
"""dictionary,tuples,setproblems.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZjKrE-3RRv9W6ygV8WnpbkNF7g8Wg_HS
"""

#Create a dictionary with given key-value pair:
dict1 ={'table':'a piece of furniture,list of facts and figures','cat':'a small animal'}
print(dict1)

#Print only unique subjects:
subjects ={"C++","Java","Python","Javascript","Python","Java","C","C++"}
print(len(subjects))
print(subjects)

#Take marks from user for 3 subjects:
marks = {}
x = int(input("Enter marks of Physics: "))
marks.update({"Physics":x})
y = int(input("Enter marks of Maths: "))
marks.update({"Maths":y})
z = int(input("Enter marks of English: "))
marks.update({"English":z})

print(marks)

#Printing same values:
values = {("float",9.0),("int",9)}

print(values)

