# -*- coding: utf-8 -*-
"""Enumerate_Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5B4HKHSMUCHfvCmLSjVGL1h91fb7SzD
"""

marks = [10,12,14,18,16,15]
for mark in marks:
  print(mark)

index=0
for mark in marks:
  print(mark)
  if (index == 3):
   print("You are the topper.")
  index = index + 1

for index,mark in enumerate(marks):
  print(mark)
  if (index == 3):
   print("You are the topper.")

fruits = ['Apple','Banana','Papaya','Mango','Fig','Kiwi']
for index,fruit in enumerate(fruits,start =1):   #can use start to specify the start of indicies.
  print(index,fruit)
  if(index == 3):
   print("This is my favorite fruit.")

Places = ('Norway','Brazil','Rome','Germany')
for index,place in enumerate(Places):
  print(index,place)
  if(index==3):
    print("Capital of Germany is Berlin.")

Places = ('Norway','Brazil','Rome','Germany')
for index,place in enumerate(Places):
  print(place)
  if(index==3):
    print("Capital of Germany is Berlin.")

Places = ('Norway','Brazil','Rome','Germany')
for index,place in enumerate(Places):
  print(index,place)
  if(place=="Germany"):
    print("Capital of Germany is Berlin.")

