# -*- coding: utf-8 -*-
"""Functions_mod2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rnYVnnXUNQaJpKQ8cV4jE4VvURZFs52E
"""

def computeHCF(a,b):
  smaller = b if a>b else a
  hcf =1
  for i in range(1, smaller + 1):
    if(a % i == 0) and (b % i == 0):
      hcf = i
  return hcf

num1 = int(input())
num2 = int(input())

print(f"The HCF of {num1} and {num2} is {computeHCF(num1,num2)}")

