# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D4_Gg__tg8X6jyxF3o70CBth0iAFsX4p
"""

def Gmean(a,b):
  mean = (a*b)/(a+b)
  print(mean)
def isGreater(a,b):
  if (a>b):
    print("a is greater than b.")
  else:
    print("b is greater than a.")
def isLesser(a,b):
  pass
a = int(input("Enter a:"))
b = int(input("Enter b:"))
isGreater(a,b)
Gmean(a,b)

def name(fname,lname):
  print("Hello!", fname,lname)
name("Suzain","Rafiq")

def average(a=1,b=2):
 print("The average is :", (a+b)/2)
average()

def average(a=1,b=2):
 print("The average is :", (a+b)/2)
average(b=3)

def average(a=1,b=2):
 print("The average is :", (a+b)/2)
average(6)

def average(a=1,b=2):
 print("The average is :", (a+b)/2)
average(12,10)

def average(a=1,b=2):
 print("The average is :", (a+b)/2)
average(b=12,a=10)

def average(a,b=2):   #a becomes default arg
 print("The average is :", (a+b)/2)
average(a=10)

def average(a,b,c=2):   #a,b becomes default arg
 print("The average is :", (a+b+c)/3)
average(a=10,b=2)

def average(*numbers):
  sum =  0
  for i in numbers:
    sum = sum + i
  print("Average is:",sum/len(numbers))
average(10,2,2)

def average(*numbers):
  sum =  0
  for i in numbers:
    sum = sum + i
  return sum/len(numbers)
c=average(10,2,2)
print(c)

