# -*- coding: utf-8 -*-
"""Global&LocalVar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eehR7jPMe2l7Sn0NmvZpJ0N5fqZhha0i
"""

x = 5
print(f"The global value of x is :{x}")

def welcome():
  global x
  x=4
  y=1
  print(f"The local value of x is :{x}")
  print("I am inside Func Body")
  print(y)
welcome()

print(f"The global value of x is :{x}")

x = "Suzain"
print(x)
def name():
  global x
  x = "Mehreen"
  print(x)

name()
print(x)

