# -*- coding: utf-8 -*-
"""Import_Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NDc27innq5lhu0LCpB9s9xVKmToG_ENP
"""

import math
c=math.sqrt(9)
print(c)

from math import sqrt,pi
c = pi
print(c)
d = sqrt(9)*pi
print(d)

from math import sqrt as s,pi as p
a = s(4)
print(a)
d = 8*p
print(d)

from math import *  #Importing everything from module to this program
result = sqrt(9)
print(result)

import math as m
print(dir(m))
print(type(m.e))

from testfile import welcome,Country

welcome()
print(Country)

from testfile import *
welcome()
print(Country)

import testfile as tf
tf.welcome()
print(tf.Country)

