# -*- coding: utf-8 -*-
"""is,==.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_m1gFSEUOpYTiCzHPg6oJ011RCSqnuHx
"""

a = 3
b = "3"

print(a is b)
print(a == b)

a = 3
b = 3

print(a is b)
print(a == b)

a = [1,2,33]
b = [1,2,33]

print(a is b)
print(a == b)

a = {1,2,33}
b = {1,2,33}

print(a is b)
print(a == b)

a = (1,2)
b = (1,2)

print(a is b)
print(a == b)

a = "Sara"
b = "Sara"

print(a is b)
print(a == b)

