# -*- coding: utf-8 -*-
"""listsproblemset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uyGxl8dFJZagJTpPZEGaXye0AvM2KtVE
"""

#Storing names of movies as a list:
movies =[]
movies.append(input("Enter the name of 1st movie:"))
movies.append(input("Enter the name of 2nd movie:"))
movies.append(input("Enter the name of 3nd movie:"))

print(movies)

#program to check if  a list is palindrome:
list1 =["m","a","a","m"]
x=list1.copy()
x.reverse()
if x ==list1:
  print("List is palindrome")
else:
  print("Not Palindrome")



