# -*- coding: utf-8 -*-
"""Lists_Mod2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z893aX6MFLLbs8i_khsNK6QH0V5aVFpy
"""

lst1 =[]
print(lst1)

lst2 =['SAM','Sana',"Joe"]
print(lst2)

lst3 =[[1,2],[3,4]]
print(lst3)

print(len(lst3))

lst3.append('five')
print(lst3)

lst3.insert(1,[5,6])
print(lst3)

lst3.remove([5,6])
print(lst3)

lst2.append(lst3)
print(lst2)

lst2.extend(lst3)
print(lst2)

lst1 = ["Hana","Zain","Joe"]
lst2 = ["Ed","Blake","Tyga"]
lst1.extend(lst2)
print(lst1)

lst1 = ['one','two','three','four','five']
del lst1[2]
print(lst1)

lst1 = ['one', 'two', 'four', 'five']
a= lst1.pop(2)
print(a)
print(lst1)

lst1 = ['one','two','three','four','five']
lst1.remove('four')
print(lst1)

lst1 = ['one','two','three','four','five']
if 'two' in lst1:
  print("Hello")
if 'six' not in lst1:
  print("Bye")

lst1 = ['one','two','three','four','five']
lst1.reverse()
print(lst1)

lst1 = [5,6,2,3,9,1]
sorted_list = sorted(lst1)
print(f"The original list is :{lst1}")
print(f"The sorted list is: {sorted_list}")

lst1 = [5,6,2,3,9,1]
sorted_list = sorted(lst1,reverse = True) #for descending order
print(f"The original list is :{lst1}")
print(f"The sorted list is: {sorted_list}")

lst1 = [5,6,2,3,9,1]
lst1.sort()
print(lst1)

lst1 = [5.4,2.2,2.1,3.5,9,1]
lst1.sort(reverse=True)
print(lst1)

s = "My-name-Is-Suzain"
s_lst=s.split("-")
print(s_lst)

s="The weather is Sunny"
s_lst = s.split()
print(s_lst)

lst1 = [1,3,4,6,7,8,9]
print(lst1[3])

lst1 = [1,3,4,6,7,8,9]
print(lst1[1:])

lst1 = [1,3,4,6,7,8,9]
print(lst1[::2])

lst1 = [1,3,4,6,7,8,9]
print(lst1[:5:2])

lst1 = [1,3,4,6,7,8,9]
print(lst1[2::2])

lst1 = [1,1,3,4,5]
lst2 =[9,8,6,9,0]
lst3 = lst1  + lst2
print(lst3)
print(lst3.count(5))

lst_1= ['one','two','three','four']
for i in lst_1:
  print(i)

squares = []
for i in range(10):
  squares.append(i**2)
print(squares)

squares =[i**2 for i in range(10)]
print(squares)

lst = [-10,-20,10,20,-15,50]
new_lst = [i*2 for i in lst]
print(new_lst)
new_lst1 =[ i for i in new_lst if i>0 ]
print(new_lst1)
new_lst2 =[(i,i**2) for i in range(2,8) ]
print(new_lst2)

matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
transposed = [[row[i] for row in matrix]for i in range(4)]
print(transposed)

