# -*- coding: utf-8 -*-
"""Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rgRMWhSCKGUKjHKaIN147bPA2CcHL3PC
"""

lst = ["Zain","3.12",0,True,"Sydney","hello",13,87]
print(lst)

print(type(lst))

print(lst[:])

print(lst[1:6])

print(lst[-2])

print(lst[5])

print(lst[:-2])

if 0 in lst:
  print("Yes")
else:
  print("No")

if "ydn" in "Sydney":
  print("Yes")

print(lst[1:6:2])

print(lst[1:6:3])

print([]) #List comprehension

lst1 =[i for i in range (4)]
print(lst1)

lst1 =[i*i for i in range (4)]
print(lst1)

lst1 =[i*i for i in range (10) if i%2==0 ]
print(lst1)

#List_Methods:
l = [ 2,10,18,13,2,4,5,8,6,9]
l.sort()

l.append(6)

l.reverse()

l.sort(reverse=True)
print(l)

print(l.index(4))

print(l)

l.count(2)

l1=[10,12,3,6,8,2,9]
m = l1.copy()
#m[0]= 0
print(l1)

l1.insert(2,32)

print(l1)

# m = [13,15,16]
# l1.extend(m)
# print(l1)

k = l1 + m
print(k)

