# -*- coding: utf-8 -*-
"""Loop_with_Else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yk3OtmTdikphtMDplE13w0N4UOFcXNh8
"""

for i in range(5):
  print(i)
else:
  print("Sorry no i ")

for i in []:
  print(i)
else:
  print("Sorry no i ")

for i in range(6):
  print(i)
  if i == 4:
    break
else:
  print("Sorry no i ")

i = 0
while i <7:
  print(i)
  i = i+1
  # if i ==4:
  # # break
else:
  print("Sorry no i")

