# -*- coding: utf-8 -*-
"""Loops(Practice).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IVaKhNJ-A__poaHoBPvlcwMm_NxVIfO8
"""

#Strings:
name = "SuzainRafiq"
for i in name:
  print(i,end = "\n")
  if i == "n":
    print("Hello Suzain")
    break

#Lists:
colors = ["Red", "Pink", "Orange","Blue"]
for color in colors:
  print(color)
  if (color == "Pink"):
   break
for j in color :
  print(j)

for i in range(1,9):
  print(i)

for i in range(-15,-1):
 print(i+1)

for k in range (1,20,4):
  print(k)

