# -*- coding: utf-8 -*-
"""Map,Filter,Reduce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uyRhNdDYTt3c-8mvoim94sTahK3e4r7M
"""

#MaP:
l = [1,1,2,4,5,6,8,7]
newl =[]
sq = lambda x : x*x
for i in l:
  newl.append(sq(i))
print(newl)

newl = map(sq,l)
print(list(newl))

numbers = [1,2,3,4]
doubled = map(lambda x:x*x,numbers)
print(list(doubled))

#FILTER:
l = [1,8,2,4,5,6,8,7]
check = lambda x:x>4

newL= filter(check,l)
print(list(newL))

num = [2,3,4,5,6,14,8]
#l_check= lambda x:x%2==0
evens= filter(lambda x:x%2==0,num)
#evens= filter(l_check,num)
print(list(evens))

#REDUCE:
from functools import reduce
numbers = [2,3,4,5,6]
sum = reduce(lambda x,y:x+y,numbers)
print(sum)

