# -*- coding: utf-8 -*-
"""Module_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gKy9i05kxm7xfqP3tRenhoR1Oss4wqBQ
"""

for i in range(10):
  print(i)

for i in range(2,7):
  print(i+1)

a = 1+2+\
3+4+\
    3
print(a)

a = 3
b = '3'
print(isinstance(3,int))

a = 10;b=20
print("The value of a is {} and b is {}".format(a,b))

a = 10;b=20
print("The value of b is {1} and a is {0}".format(a,b))

print("Hello {name}, {greeting}".format(name="Bella",greeting = "GoodMorning!"))

print("This is the story of {0},{1} and {other}".format('Bill','Sam',other = 'Tyga'))

lst = [1,3,5,6]
print(1 in lst)

d = {1:'a',3:'b'}
print(a in d)

num = -90
if num>=0:
  if num>0:
    print("Positive")
  else:
    print("Zero")
else:
  print("Negative")

num1 = 1000
num2 = 20
num3 = 155
if(num1>= num2) and (num1>=num3):
    print("Num1 is largest")
elif(num2>=num1) and (num2>=num3):
    print("Num2 is largest")
else:
    print("Num3 is largest")

lst = [10,20,30,40,60]

product = 1
index = 0

while index < len(lst):
    product *=lst[index]
    index += 1


print(f"The product is {product}")

numbers = [1,2,3,4,5,6]

index = 0
while index<len(numbers):
    print(numbers[index])
    index +=1

else:
    print("This is the end of list")

numbers = [1,2,3,4,5,6]
for i in numbers:
  print(i)
else:
  print("This is the end of list")

num = int(input("Enter the number: "))
isDivisible = False
i = 2
while i < num:
    if num%i == 0:
     isDivisible = True
     print(f"{num} is divisible by {i}")
    i +=1
if isDivisible==True:
    print(f"{num} is not a prime number")
else:
    print(f"{num} is a prime number")

lst1 = [10,20,30,40,50]
product = 1
for i in lst1:
  product *=i
print("The product is", product)

lstx = ["Zaid","Shenu","Fakhir","Elsa"]
for index in range(len(lstx)):
  print(lstx[index])
for i in lstx:   #Both yield same result
  print(i)

numb = [1,2,3,4]
for num in numb:
  print(num)
else:
  print("End of list")

index1 = 10
index2 = 50
for num in range(index1,index2 +1):
  if num>1:
    isDivisible = False
    for index in range(2,num):
      if num % index ==0:
       isDivisible = True
    if not isDivisible:
     print(num)

for num in range(0,10):
  if num == 4:
    break
  print(num)
else:
  print("GoodMorning")
print("Hello")

for num in range(0,10):
  if num == 4:
    continue
  print(num)
else:
  print("GoodMorning")
print("Hello")

numbers = [1,3,2,4,5,7]
for num in numbers:
  if num%2 ==0:
    continue
  print(num)
else:
  print("Else block")

