# -*- coding: utf-8 -*-
"""Problem_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1284RLSBvTsppkSiThTv00TRbq0aL8rYY
"""

def is_leap(year):
    leap = False

    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                leap = True
        else:
            leap = True
    return leap
year = int(input())
print(is_leap(year))

