# -*- coding: utf-8 -*-
"""PythonProblem_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eX2hGANO93IA7f9WdAKR-sb69Cx0DTDK
"""

a = int(input())
 b = int(input())
x = a//b
y = a/b
print(x)
print(y)

def swap_case(s):
    return s.swapcase()
if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

def split_and_join(line):
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)