# -*- coding: utf-8 -*-
"""PythonProblem#1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HJ0WWzzoU1gsL25dn5XDSyWjGIRi50Dg
"""

n = int(input("n is: "))
if n%2!= 0:
    print("Weird")
elif n % 2 == 0 and 2 <=n <=5:
    print("Not Weird")
elif n % 2 == 0 and 6 <=n <=20:
    print("Weird")
elif n %2  and n>20:
    print("Not Weird")

def print_full_name(first, last):
    if len(first) <= 10 and len(last) <= 10:
        print(f"Hello {first} {last}! You just delved into python.")
first_name = input("")
last_name = input("")
print_full_name(first_name, last_name)