# -*- coding: utf-8 -*-
"""Recursion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10mcrGsGjT4eBzVombQeL3LVxTq4gTTQP
"""

import this

def square(n):
  '''Take the value for n and return it's square'''
  print(n*2)
square(4)
print(square.__doc__)

def factorial(n):
  if (n == 0 or n == 1):
    return 1
  else:
   return  n * factorial(n-1)
n = int(input("Enter value for n: "))
#result = factorial(n)
print(factorial(n))

def fib(n):
  if (n == 0):
    return 0
  elif(n ==1):
    return 1
  else:
   return  fib(n-1)+fib(n-2)
n = int(input("Enter value for n: "))
print(fib(n))

