# -*- coding: utf-8 -*-
"""ShortHandIfElse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GYe62KLvfpj0S56FIsTkqz0yN2owv2Jq
"""

a = int(input("Enter the value for a: "))
b = int(input("Enter the value for b: "))
print("A is greater") if a>b  else print("Both values are same") if a==b else print("B is greater")

a = int(input("Enter the value for a: "))
b = int(input("Enter the value for b: "))
print("B") if b>a else print("Both are same") if b==a else print("A")

print(9+10) if a>b  else " "

print("Hello") if a<b else 0

c=10 if a>b else 0
print(c)

num = int(input("Enter the value: "))
print("The number is even.") if num%2 ==0 else print("The number is odd.")

