# -*- coding: utf-8 -*-
"""string_split_join.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0Rvd8hSPCNd3En0sP0eUj4IVMY-qg7t
"""

def split_and_join(line):

 if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)