# -*- coding: utf-8 -*-
"""Studebtgrades.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18FgG6xd9wdaFj15fsje-ql3dYgcso477
"""

#Grading students based on marks:
marks = int(input("Enter marks: "))
if marks >=90:
  Grade =" A"
elif marks>=80 and marks <90:
  Grade = "B"
elif  marks>=70 and marks <80:
  Grade = "C"
else:
  Grade = "D"
print("Your grade is: ", Grade)

