# -*- coding: utf-8 -*-
"""tupleproblem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WmG5QE92ke5PXHA4dhnMZCCECOlcZFNk
"""

grade = ("C","D","A","A","B","B","A")
print(grade.count("A"))

grade = ["C","D","A","A","B","B","A"]
grade.sort()
print(grade)

