# -*- coding: utf-8 -*-
"""Tuples_Mod2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SkM_mAUCV_eMn_iN1ew3tY7BTAwDEQuO
"""

tup=()
print(type(tup))

t = (1,2,4,['Sam','Leo'],(3,5))
print(t)

t =('Sana')
type(t)

t =('Sana',)
print(type(t))

t = ('Sana','Zaian','Theo','Bella')
print(t[3])

t = ('Sana',('Zaian','Theo','Rayn'),'Bella')
print(t[1])
print(t[1][2])

t =(1,3,4,[5,6,8])
t[3][1]= "Satish"
print(t)

t= ("Satish ",)*3
print(t)
print(type(t))

t =(1,3,4,[5,6,8])
 del t
 print(t)

t =(1,3,4,[5,6,8],1,2,3,1)
t.count(1)

t =(1,3,4,[5,6,8],1,2,3,1)
print(t.index(3))

t =(1,3,4,[5,6,8],1,2,3,1)
print (1 in t)

t =(1,3,4,[5,6,8],1,2,3,1)
print(1 not in t)

t =(1,3,4,[5,6,8],1,2,3,1)
print(len(t))

t =(1,3,4,1,2,3,1)
new_tup=sorted(t,reverse=True)
print(new_tup)

t =(1,3,4,1,2,3,1)
print(max(t))
print(min(t))
print(sum(t))

